apiVersion: apps/v1
kind: Deployment
metadata:
  name: dereferbot
  labels:
    app.kubernetes.io/name: dereferbot
    app.kubernetes.io/created-by: zoomoid
spec:
  selector:
    matchLabels:
      app.kubernetes.io/app: dereferbot
  template:
    metadata:
      labels:
        app.kubernetes.io/app: dereferbot
    spec:
      securityContext:
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
      containers:
      - name: dereferbot
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
              - "ALL"
        env:
          - name: DEREFER_BOT_TOKEN
            valueFrom:
                secretKeyRef:
                  name: dereferbot-token
                  key: DEREFER_BOT_TOKEN
                  optional: true
          - name: DEREFER_BOT_NAME
            valueFrom:
                secretKeyRef:
                  name: dereferbot-token
                  key: DEREFER_BOT_NAME
                  optional: true
        image: ghcr.io/zoomoid/dereferbot:latest
        imagePullPolicy: Always
        resources:
          limits:
            memory: "128Mi"
            cpu: "200m"
